### ISSUE TITLE
Support for PowerDNS 4.x

### ISSUE THREAD

**Issue by jgreat** [jgreat/powerdns#1]
Looks like the PowerDNS API has changed in 4.x. 

Investigate some kind of version detection and updating paths. 

https://github.com/rancher/rancher/issues/6136

**Comment by janeczku** [comment]
Maybe derive the version from the base URL specified by the user when constructing the client?
v3.x base URL : http://server/
v4.x base URL : http://server/api/v1

**Comment by dmportella** [comment]
i am working on this

**Comment by jgreat** [comment]
closed, this project is pretty dead
